// This file is auto-generated by Wails (wails dev or wails build).
// Regenerate by running: wails dev
// Do not edit manually.

export function ListCommands(stageId: string): Promise<any[]> { return window.go.main.App.ListCommands(stageId); }
export function CreateCommand(title: string, stageId: string): Promise<any> { return window.go.main.App.CreateCommand(title, stageId); }
export function UpdateCommand(id: number, title: string, status: string, stageId: string): Promise<any> { return window.go.main.App.UpdateCommand(id, title, status, stageId); }
export function DeleteCommand(id: number): Promise<void> { return window.go.main.App.DeleteCommand(id); }
export function ReorderCommands(byStageId: Record<string, number[]>): Promise<void> { return window.go.main.App.ReorderCommands(byStageId); }
export function GetBoard(): Promise<any> { return window.go.main.App.GetBoard(); }
export function UpdateBoard(name: string): Promise<any> { return window.go.main.App.UpdateBoard(name); }
export function UpdateStageLabels(labels: Record<string, string>): Promise<any> { return window.go.main.App.UpdateStageLabels(labels); }
export function ResetBoard(): Promise<void> { return window.go.main.App.ResetBoard(); }
export function GetActiveSession(): Promise<any> { return window.go.main.App.GetActiveSession(); }
export function StartSession(commandId: number): Promise<any> { return window.go.main.App.StartSession(commandId); }
export function StopSession(): Promise<void> { return window.go.main.App.StopSession(); }
export function GetLatestSessionsByStageId(): Promise<Record<string, any>> { return window.go.main.App.GetLatestSessionsByStageId(); }
export function ListOutcomes(commandId: number): Promise<any[]> { return window.go.main.App.ListOutcomes(commandId); }
export function CreateOutcome(commandId: number, note: string): Promise<any> { return window.go.main.App.CreateOutcome(commandId, note); }
export function DeleteOutcome(outcomeId: number): Promise<void> { return window.go.main.App.DeleteOutcome(outcomeId); }
export function ListSnapshots(): Promise<any[]> { return window.go.main.App.ListSnapshots(); }
export function SaveSnapshot(name: string): Promise<any> { return window.go.main.App.SaveSnapshot(name); }
export function LoadSnapshot(snapshotId: number): Promise<void> { return window.go.main.App.LoadSnapshot(snapshotId); }
export function DeleteSnapshot(snapshotId: number): Promise<void> { return window.go.main.App.DeleteSnapshot(snapshotId); }
export function RenameSnapshot(snapshotId: number, name: string): Promise<any> { return window.go.main.App.RenameSnapshot(snapshotId, name); }
export function GetFocusData(stageId: string): Promise<any> { return window.go.main.App.GetFocusData(stageId); }

declare global {
  interface Window {
    go: {
      main: {
        App: {
          ListCommands(stageId: string): Promise<any[]>;
          CreateCommand(title: string, stageId: string): Promise<any>;
          UpdateCommand(id: number, title: string, status: string, stageId: string): Promise<any>;
          DeleteCommand(id: number): Promise<void>;
          ReorderCommands(byStageId: Record<string, number[]>): Promise<void>;
          GetBoard(): Promise<any>;
          UpdateBoard(name: string): Promise<any>;
          UpdateStageLabels(labels: Record<string, string>): Promise<any>;
          ResetBoard(): Promise<void>;
          GetActiveSession(): Promise<any>;
          StartSession(commandId: number): Promise<any>;
          StopSession(): Promise<void>;
          GetLatestSessionsByStageId(): Promise<Record<string, any>>;
          ListOutcomes(commandId: number): Promise<any[]>;
          CreateOutcome(commandId: number, note: string): Promise<any>;
          DeleteOutcome(outcomeId: number): Promise<void>;
          ListSnapshots(): Promise<any[]>;
          SaveSnapshot(name: string): Promise<any>;
          LoadSnapshot(snapshotId: number): Promise<void>;
          DeleteSnapshot(snapshotId: number): Promise<void>;
          RenameSnapshot(snapshotId: number, name: string): Promise<any>;
          GetFocusData(stageId: string): Promise<any>;
        };
      };
    };
  }
}
